# This is a basic workflow to help you get started with Actions
name: CI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
      # Runs a single command using the runners shell
      name: CI test build maven 
      uses: ./.github/workflows/buildreuse.yml
      with: 
          path_to_settings: .maven/settings.xml
          path_to_pom: pom.xml
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:  
      - name: CD sandbox from Main
        if: ${{ github.event.ref == 'refs/heads/main' }}
        run: echo "deffm"
        #uses: ./.github/workflows/deployreuse.yml
      
      - name: CD sandbox from Dev
        if: ${{ github.event.ref == 'refs/heads/Dev' }}
        run: echo "dev"
        
      - name: CD sandbox from UAT
        if: ${{ github.event.ref == 'refs/heads/UAT' }}
        uses: ./.github/workflows/deployreuse.yml
        with:
          CLOUDHUB_ENVIRONMENT: "prod-01"
          GITHUB_ENVIRONMENT: "prod"      
          CLOUDHUB_WORKERS: "1"
          CLOUDHUB_WORKER_TYPE: "MICRO"
          CLOUDHUB_REGION: "ca-central-1"
          HTTP_PRIVATE_PORT: "8091"      
        #secrets:
         # CLOUDHUB_USERNAME: ${{ secrets.CLOUDHUB_USERNAME }}        
          #CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}
