name: Deploy to Sandbox

on:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
    - name: Deploy to Sandbox
      env:
        USERNAME: ${{ secrets.anypoint_platform_username }}
        PASSWORD: ${{ secrets.anypoint_platform_password }}
       # KEY: ${{ secrets.decryption_key }}
      #run: echo "kk"
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn clean deploy -DmuleDeploy \
        -Dmule.artifact=$artifactName \
        -Danypoint.username="$USERNAME" \
        -Danypoint.password="$PASSWORD"
